image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm config set registry https://registry.npm.taobao.org
  - npm install hexo-cli -g
  - npm install
  - hexo g
  artifacts:
    paths:
    - public
  only:
  - master
