# Icon
favicon: /favicon.ico
# SEO
keywords: Hexo, Gruntjs, Nodejs, Reactjs, Vuejs
# Header
page_background: /wrapper.jpg
page_menu_button: dark
post_background: /wrapper.jpg
post_menu_button: light
title_plancehold: 随笔
author:
  head: /avatar.png
  signature: Only when you plant the flowers can you really smell their fragrance.
navication:
  - name: Github
    link: https://github.com
  - name: V2EX
    link: https://www.v2ex.com/
# content
content_width: 800
# Footer
## Social icon list: [facebook, twitter, weibo, wechat, github, stackoverflow, linkin, email, segmentfault, flickr, zhihu, disqus, douban, bilibili]
social:
  - name: Github
    icon: github
    link: https://github.com/
#  - name: Weibo
#    icon: weibo
#    link: https://weibo.com/heqibang
#  - name: SegmentFault
#    icon: segmentfault
#    link: https://www.segmentfault.com/u/bon
# Duoshuo
duoshuo:
  enable: false
  siteName: ueibo
# Copyright
copyright:
  record: false
  hexo: true
  laughing: true